version: '2'

services:
  etcd:
    image: docker.io/bitnami/etcd:3.5
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    volumes:
      - /usr/local/var/etcd:/bitnami/etcd
    ports:
      - "2379:2379"
      - "2380:2380"
volumes:
  etcd_data:
    driver: local
