version: '2'

networks:
  app-tier:
    driver: bridge

services:
  redis:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=master
      - REDIS_PASSWORD=str0ng_passw0rd
      - REDIS_REPLICA_IP=127.0.0.1
      - REDIS_REPLICA_PORT=54411    
    networks:
      - app-tier
    ports:
      - 6379
  redis-slave:
    image: 'bitnami/redis:latest'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
      - REDIS_PASSWORD=str0ng_passw0rd
      - REDIS_REPLICA_IP=127.0.0.1
      - REDIS_REPLICA_PORT=54410
    depends_on:
      - redis
    networks:
      - app-tier
    ports:
      - 6379    
  redis-sentinel1:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26379:26379'
    networks:
      - app-tier
  redis-sentinel2:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26380:26379'
    networks:
      - app-tier
  redis-sentinel3:
    image: 'bitnami/redis-sentinel:latest'
    environment:
      - REDIS_MASTER_PASSWORD=str0ng_passw0rd
    depends_on:
      - redis
      - redis-slave
    ports:
      - '26381:26379'
    networks:
      - app-tier
